DisablePathCorrection = false
EnablePathEscape = false
FireMethodNotAllowed = true
DisableBodyConsumptionOnUnmarshal = false
TimeFormat = "Mon, 01 Jan 2006 15:04:05 GMT"
Charset = "UTF-8"

[Other]
  UseProcessors = 2
	MyServerName = "d02"
  MyAddress = "192.168.1.194"
  MyPortShift = 5020
#  JoinCluster = ["192.168.1.194:5000","192.168.1.194:5200"]
  JoinCluster = ["192.168.1.194:5000"] #testing setting, make 2nd node know only first node
  ClusterAcceptPattern = "^192\\.168\\."
  GoogleMapApiKey = ""